"""Removed user role

Revision ID: 0c4318976d62
Revises: 6e7ada5ee3e2
Create Date: 2024-11-29 01:13:47.638296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4318976d62'
down_revision: Union[str, None] = '6e7ada5ee3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
