"""Updated Relationships

Revision ID: 6e7ada5ee3e2
Revises: b2b6b41e0ba3
Create Date: 2024-11-29 00:46:13.799058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7ada5ee3e2'
down_revision: Union[str, None] = 'b2b6b41e0ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
